### ISSUE TITLE
3.6 - lseek Function

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#1]
Starting on or around the 9th line below the title, "lseek Function," 
       - If whence is SEEK_SET, the file's offset is set to offset bytes from the beginning of the file. 
          off_t lseek ( int fields, off_t offset, int whence );

```
   Question : If whence is SEEK_SET, yet the parameter says int whence. I am confused by this. Could you clarify ? Where is SEEK_SET coming from ?
```

**Comment by johnwfinigan** [comment]
Sure, just to clarify: whence is a formal parameter name, it's the "placeholder name" in the function's prototype. SEEK_SET is one of the valid values you are allowed to pass as an argument when you call lseek. It's defined in unistd.h like this:

```
 # define SEEK_SET  0   /* Seek from beginning of file.  */
```

So basically, it's just a constant with value 0, on our system.
