### ISSUE TITLE
The for loop

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#11]
I am not understanding this, and would like your feedback..
 What is strnlen in the homework ? Is it the very functionality of strnlen, and we are just analyzing this function ?

In looking at  
for (cp = str; maxlen != 0 && *cp != '\0'; cp++, maxlen--)
        ;

```
return (size_t)(cp - str);
```

 Regardless, I will send this homework, however, if you will be around school anytime monday, tuesday etc- please let me know so I can come and talk with you. Thanks.

**Comment by johnwfinigan** [comment]
The only purpose of using strnlen in particular is that it is a tiny function that also has a manpage. The idea is just to do a close reading of all of the generic function related syntax.

I'll be around all week next week, pretty much normal daytime hours.
