### ISSUE TITLE
scp 

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#12]
I tried looking for the previous issues regarding the scp, for copying the ssh c file to local files. I could not find it. Could you re-display the command to do this.

Thankyou.

**Comment by johnwfinigan** [comment]
If you look at the issues page, you should see at the top of the list of issues, the word "closed", probably with a checkmark next to it. If you click on the word closed, you should see all of the older issues.

Let me know if you don't find it and I'll help.

**Comment by johnwfinigan** [comment]
Another way: if you see the issues search box that says "Filters", put in the search term `is:closed`
