### ISSUE TITLE
Using printf to display lseek.

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#3]
I cannot find good information on how to display whatever the offset is set on from lseek

If lseek  returns bytes, what printf mode allows one to see what was sought out?

Thanks.

**Comment by johnwfinigan** [comment]
Quick answer - lseek returns off_t. There is no specific printf format code for off_t, but as a rule of thumb, it's usually OK to cast aliased integer types to `(long long)` and use the format code `%lld`

Longer - But this is only strictly reasonable if the aliased type is actually a signed integer type. If it's an unsigned integer, something incorrect may be printed out if the value in the variable is larger than the positive max of a signed long long.

So is off_t signed? Yes, see http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html  (and search the text of this page for off_t -- off_t is part of the Single UNIX Specification / POSIX standard, not the C11 standard)
