### ISSUE TITLE
Upload one .c file

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#8]
Thank you for last issue response.

Regarding this, is there an easy way to get the c file in cook, and have it placed within local file system?

**Comment by sneupan3** [comment]
You can use the Secure Copy (scp) command in order to copy file from the remote directory to your local machine. In our case, you can do the following:
 scp your_username@cook.cs.uno.edu:your_file.c /localDirectory(you can just have a dot here to copy to the current directory in your local machine)

**Comment by ghost** [comment]
Thanks

**Comment by johnwfinigan** [comment]
SCP is definitely a good choice. Another one you might want to try (both are useful) is SFTP.

SFTP looks just like command line FTP except it works over an encrypted connection.

https://www.digitalocean.com/community/tutorials/how-to-use-sftp-to-securely-transfer-files-with-a-remote-server

**Comment by ghost** [comment]
scp user_name@cook.cs.uno.edu:2467-work/hmwk3.c ~/.

This worked. I am putting this up, if anyone else comes to an issue with this. The ~ made a difference for whatever reason.

**Comment by sneupan3** [comment]
The ~ takes you to the home directory and copies the file there.
Try only using the "." after the space and it copies the file to your present working directory in terminal.

**Comment by johnwfinigan** [comment]
Right. One way to think of it (and this is an analogy, not literal reality) is that the dot like a variable name that evaluates to your current working directory in your shell, and the `~` is like a variable name that evaluates to the path of your home directory, no matter what.

We have two variables in the shell that are exactly what I say above, not just an analogy. Try these two commands at the shell:

```
 echo $HOME
 echo $PWD
```

Echo is a shell command that prints things, including the contents of shell variables, which it recognizes when the variable name follows a $ sign, just like above.

In this case, dot works like `$PWD`, and `~` works like $HOME

When you do that scp command, it takes two arguments - the source, that is, the file you're making a copy of, and the destination, that is, the copy to be created.

If you used `./myfile.c` as the source, the dot gets evaluated as `$PWD/myfile.c` and `$PWD` is evaluated _locally_. If you used `~` as the destination, it would create a file with the same name at `$HOME` on the remote system, where `$HOME` is evaluated _remotely_.
